# -*- coding: utf-8 -*-
"""Deep bugs.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MuhEb5-ow0aPoZEarISCivB2pfxxVcC_
"""

# NETWORK ARCHITECTURE
# INPUT (Dropout 20%)
# HIDDEN (Dense 200 + ReLU + Dropout 20%)
# OUTPUT (Dense 1 + Sigmoid)

# Compile w binary_crossentropy loss and the rmsprop optimizer.
# Train for 10 epochs. Batch size 100

#Libraries to create the multiclass model
from keras.models import Sequential
from keras.layers import Dense
from keras.wrappers.scikit_learn import KerasClassifier
from keras.utils import np_utils

#Import tensorflow and disable the v2 behavior and eager mode
import tensorflow as tf
tf.compat.v1.disable_eager_execution()
tf.compat.v1.disable_v2_behavior()


def basemodel():
  model = Sequential() 

  #Adding 20% dropout 
  model.add(Dropout(0.20))

  #Add 1 layer with output 200 and relu function
  model.add(Dense(200,activation='relu'))

  #Adding 20% dropout here
  model.add(Dropout(0.20))

  #Add 1 layer with output 1 and sigmoid function 
  model.add(Dense(1,activation='sigmoid'))

  return model

model = basemodel()

#Compile the model using binary_cross loss function and rmsprop optim
model.compile(loss='binary_crossentropy',optimizer='rmsprop', metrics=['accuracy'])

model_mdata = model.fit(data_train, labels_train, validation_data=(data_test, labels_test), epochs=10, batch_size=100, shuffle=True)

#FILL THIS IN
scores = model.evaluate(data_test, labels_test)
print("Accuracy: %.2f%%"%(scores[1]*100))