name: github-ci
on: [push]
jobs:

  build_main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: pip3 install gensim
      - run: python3 deepbugs_jr.py

  build_extract_token_from_ast_node:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: pip install gensim mypy
      - run: mypy ast_token_extractor.py
      - run: python3 ast_token_extractor.py
  
  build_swarg_generate_training_eval_dataset:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: pip3 install mypy
      - run: mypy gen_train_eval.py
      - run: python3 gen_train_eval.py
      
  build_swarg_fnarg_extract:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: pip3 install mypy
      - run: mypy swarg_fnargs2tokens.py
      - run: python3 swarg_fnargs2tokens.py
      
  build_tokens_popularity:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      #- run: mypy 
      #- run: python3 
      

  test_main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: pip3 install gensim
      - run: python3 -m unittest
