name: github-ci
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: git checkout develop
      - run: python3 deepbugs_jr.py
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: git checkout develop
      - run: python3 -m unittest
