name: github-ci
on: [push]
jobs:

  build_main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: pip3 install gensim
      - run: python3 deepbugs_jr.py

  build_ast2tok:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: python3 ast_token_extractor.py
  
  test_main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: pip3 isntall gensim
      - run: python3 -m unittest
