name: github-ci
on: [push]
jobs:
  word2vec:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
      - name: Set up gensim
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt
      - run: pip3 list gensim


  build_main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: python3 deepbugs_jr.py

  build_ast2tok:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: python3 ast_token_extractor.py
  
  test_main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: python3 -m unittest
