name: github-ci
on: [push]
jobs:
  build_main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: python3 deepbugs_jr.py
  build_ast2tok:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: pip install gensim
      - run: mypy ast_token_extractor.py
      - run: python3 ast_token_extractor.py
  test_main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: python3 -m unittest
